### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by lezabour** [lems111/bittrex-node-client#1]
Hi,
i'm trying to install & conf your app to test it.
But it seams it's missing a lot of files/directory in the app/public/ to work
as you can see here
is there any configuration to do?

<img width="805" alt="capture d ecran 2017-09-18 a 12 09 22" src="https://user-images.githubusercontent.com/3315558/30537514-3fd808ea-9c6a-11e7-9fdb-6beb9cc4d320.png">

thanks for help

**Comment by lems111** [comment]
hello @lezabour,
I am assuming that you have the node app running to support serving the files to the browser?
Here is the snippet where express is configured to serve jquery, bootstrap, etc from the node_modules folder:

![image](https://user-images.githubusercontent.com/1113806/30542885-0158c2dc-9c4f-11e7-867d-fd354f13bb9f.png)

I am assuming that you've tried to run this app on your local machine already to confirm that it's working there?
I'll need a better place to put the demo app for anyone to see; but, in the meantime, you can go here to look at the client running **(do not use this to trade)** - [bittrex node client demo](https://www.devluismiranda.com)

**Comment by lems111** [comment]
@lezabour , I haven't heard back on this. Am closing issue for now.
